name: update topios100 daily

on:
  workflow_dispatch:  # Trigger manually
  schedule:
    - cron: "00 12 * * *"

jobs:
  scrape-app-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Ensure your required version is used

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp aiohttp_socks DataRecorder pandas DrissionPage python-dotenv app_store_scraper requests

      - name: Run scraper and save results
        run: |
          python get-top100-app-daily.py
        env:
          RESULT_FOLDER: ./result  # Adjust if necessary
          OUTPUT_FOLDER: ./output
      - name: upload files          
        uses: actions/upload-artifact@v4
        with:
            name: healthapps
            path: ./result/ # or path/to/artifact
