name: Analyze App Rankings

# Set up schedule or trigger on push
on:
    workflow_dispatch:

  # push:
    # branches:
      # - main  # Trigger on changes to the 'main' branch
    # paths:
      # - appstore.py  # Trigger if this script changes
  # schedule:
    # - cron: '0 0 * * *'  # Run once per day at midnight (UTC)

jobs:
  analyze:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas matplotlib seaborn

      # Step 4: Run the Python script for analysis
      - name: Run Analysis Script
        run: |
          python top100-report.py

      # Step 5: Upload generated reports (CSV and PNG)
      - name: Upload analysis report as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-rank-analysis-report
          path: |
            significant_rank_changes.csv
            top_gainers.csv
            category_trends.csv
            category_trends.png
            top_gainers.png
